<template>
  <div class="ma-6">
    <template v-if="$i18n.locale === 'deu'">
      <h3 class="title font-weight-light primary--text mb-4">Metadaten-Leitlinie</h3>
      <p>Metadaten beschreiben die in u:scholar hochgeladenen Dokumente und Materialien inhaltlich, administrativ und technisch. Die während eines Uploads von den Nutzer*innen eingegebenen Metadaten unterliegen einer funktionalen Kontrolle durch das <a href="/info/contact">Repository Management der Universitätsbibliothek</a>.</p>

      <p>Die – auch kommerzielle – Nutzung, Weitergabe und Bearbeitung der durch u:scholar bereitgestellten Metadaten (davon ausgenommen sind rechtlich geschützte Abstracts) ist von der Universität Wien ausdrücklich erwünscht und eine Angabe zur Herkunft der Metadaten dabei nicht erforderlich. Dies entspricht den Nutzungsrechten, die durch die Lizenz <a target="_blank" href="https://creativecommons.org/share-your-work/public-domain/cc0/">CC0</a> erteilt werden.</p>

      <p>Die mit u:scholar gespeicherten Dokumente und Materialien müssen während des Upload-Prozesses mit bestimmten beschreibenden Informationen (Metadaten) versehen werden. Zu diesen <strong>Pflichtangaben</strong> gehören:</p>

      <ul>
      <li>Titel</li>
      <li>Autor*in</li>
      <li>Organisationszugehörigkeit</li>
      <li>Version</li>
      <li>Erscheinungsdatum</li>
      <li>Sprache</li>
      <li>Erscheinungsform</li>
      <li>Zugriffsrechte, inklusive Embargofrist</li>
      <li>Lizenz</li>
      </ul>
      <br/>
      <p>Darüber hinaus können weitere, <strong>optionale Angaben</strong> gemacht werden.</p>

      <p>Jede hochgeladene Datei erhält einen <strong>Persistent Identifier</strong> (z. B. <a target="_blank" href="https://phaidra.univie.ac.at/o:337723">https://phaidra.univie.ac.at/o:337723</a>), der mit den zugehörigen Metadaten verknüpft ist.</p>

      <p>Darüber hinaus werden einige <strong>technische Metadaten</strong> von der verwendeten Software Fedora Commons automatisch generiert, z.B. Zeitpunkt des Uploads, MIME-Type und Dateigröße.</p>
    </template>
    <template v-else>
      <h3 class="title font-weight-light primary--text mb-4">Metadata policy</h3>
      <p>Metadata are used to describe the content alongside technical and administrative properties of documents and materials uploaded to u:scholar. Metadata entered by users during the submission process are checked and amended by the <a href="/info/contact">University Library's repository management</a>.</p>

      <p>The usage, sharing and re-use of these metadata is explicitly supported by the University of Vienna University, even for commercial purposes (with the exception of copyright protected abstracts). Therefore no metadata provenance has to be declared. These usage rights conform to the <a href="https://creativecommons.org/share-your-work/public-domain/cc0/">CC0 license</a>.</p>

      <p>Documents and materials submitted to u:scholar have to be annotated with descriptive metadata during the submission process. <strong>Mandatory fields</strong> are:</p>

      <ul>
      <li>Title</li>
      <li>Author</li>
      <li>Affiliation</li>
      <li>Version</li>
      <li>Publication date</li>
      <li>Language</li>
      <li>Publication type</li>
      <li>Access rights and embargo period, if applicable</li>
      <li>Licence</li>
      </ul>
      <br/>
      <p>A number of <strong>optional fields</strong> are also available.</p>

      <p>Every uploaded file is assigned a <strong>persistent identifier</strong> (e. g. <a target="_blank" href="https://phaidra.univie.ac.at/o:337723">https://phaidra.univie.ac.at/o:337723</a>), which is linked to the metadata</p>

      <p>Some technical metadata is automatically generated by the Fedora Commons software used, e. g. timestamp of the upload, MIME-type and file size.</p>
    </template>
  </div>
</template>

<script>
export default {}
</script>
