<template>
  <div class="ma-6">
    <template v-if="$i18n.locale === 'deu'">
      <h3 class="title font-weight-light primary--text mb-4">Nutzungsbedingungen</h3>
      <p>Die durch den Publikationsservice u:scholar zugänglichen Dokumente und Materialien sowie dazugehörige Abstracts unterliegen dem geltenden Urheberrechtsgesetz und können zu wissenschaftlichen und privaten Zwecken frei verwendet werden. Es können jeweils unterschiedliche Nutzungsbefugnisse gelten, die den Dokumenten und Materialien sowie Abstracts zugeordnet sind.</p>
      <p>Die Rechteinhaberin oder der Rechteinhaber (nachfolgend nur "Rechteinhaber") haben der Betreiberin, der Universität Wien, das nicht-ausschließliche Recht zur elektronischen Speicherung, insbesondere in Datenbanken, zur öffentlichen Zugänglichmachung und Verbreitung sowie Sendung überlassen. Auch die Archivierung und Vervielfältigung ist der Betreiberin gestattet, wenn dies für die vorgenannten Zwecke erforderlich sein sollte. Des Weiteren hat die Betreiberin das Recht zur Meldung und Weitergabe an Dritte, insbesondere zum Zwecke der Langzeitarchivierung. Aus gleichem Zweck ist der Betreiberin das Erstellen von Kopien und die Konvertierung in andere elektronische oder physische Formate unter Wahrung der inhaltlichen Integrität gestattet. Die Betreiberin behält sich das Recht vor, ohne die Zustimmung des Rechteinhabers einholen zu müssen, die technische Infrastruktur für den Betrieb an einen Dritten auszulagern, sofern keine verwertungsrechtlichen Hindernisse dem entgegenstehen.</p>
      <p>Der Rechteinhaber versichert gegenüber der Betreiberin, dass durch die zu veröffentlichenden Dokumente und Materialien oder Teile davon (z. B. Bilder) sowie Abstracts keine Rechte Dritter (z.B. Miturheber, Verlage, Drittmittelgeber) verletzt werden. In Zweifelsfällen oder bei Entstehen vermeintlicher oder tatsächlicher diesbezüglicher Rechtshindernisse verpflichten sie sich, die Betreiberin hiervon unverzüglich in Kenntnis zu setzen. Der Rechteinhaber stellt die Betreiberin von etwaigen Ansprüchen Dritter frei.</p>
    </template>
    <template v-else>
      <h3 class="title font-weight-light primary--text mb-4">Terms of use</h3>
      <p>The documents, materials and abstracts accessible through the publication service u:scholar are governed by applicable copyright laws and may be used freely for academic and personal purposes. Different rights of use may apply for each individual document and/or material as well as abstracts.</p>
      <p>The rights holder or the copyright holder (hereinafter simply referred to as "rights holder") have granted the University of Vienna as the service operator the non-exclusive right to electronic storage, particularly in databases, for public access, distribution and electronic transmission. Furthermore, the service operator is also permitted to archive and copy data if this should be required for the above purposes. In addition, the service operator has the right to notify third parties of the content and distribute it to them, particularly for the purpose of long-term preservation. For the same purpose, the service operator is permitted to make copies and to convert the material to other electronic or physical formats while preserving the integrity of the content. The service operator reserves the right to outsource the technical infrastructure for the operation with a third party without having to obtain the consent of the owner, provided there are no legal restrictions.</p>
      <p>The rights holder assures the service operator that no rights of third parties (e.g. co-authors, publishers, funding institutions) will be violated in publishing these documents, materials or parts thereof (e.g. images) as well as abstracts. In cases of doubt or the perceived or actual occurrence of related legal restrictions, the rights holder is to immediately inform the service provider. The rights holder agrees to indemnify the operator from any third-party claims.</p>
    </template>
  </div>
</template>

<script>
export default {}
</script>
